config/routes.rb
Dtscms::Application.routes.draw do
  
  resources :descriptions

  resources :models

  resources :brands

  root "pages#home"
  
  get "/home", to: "pages#home", as: "home"
  
  get "/signin", to: "sessions#new", as: "signin"
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: "signout"
  
  namespace :admin do
    root "base#index"
    resources :users
  end
    
end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/models/description.rb
include ActionView::Helpers::SanitizeHelper

class Description < ActiveRecord::Base

  belongs_to :brand
  belongs_to :model

  # before_save :strip_html
  def strip_html # Automatically strips any tags from any string to text typed column
    self.description = strip_tags(description)
  end

end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :brand
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Use friendly_id on Users
  extend FriendlyId
  friendly_id :friendify, use: :slugged
  
  # necessary to override friendly_id reserved words
  def friendify
    if username.downcase == "admin"
      "user-#{username}"
    else
      "#{username}"
    end
  end
  
  # Use a secure password
  has_secure_password
  
  # Basic validations
  validates :username,:email, presence: true
  validates :username, length: { in: 4..10 }
  validates :username, uniqueness: { case_sensitive: false }
  validates :email, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 4 }, on: :create
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
  validates_format_of :username, with: /\A[a-zA-Z0-9]*\z/, on: :create, message: "can only contain letters and digits"
  
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  before_action :set_model, only: [:show, :edit, :update, :destroy]

  # GET /models
  # GET /models.json
  def index
    @models = Model.all.order("brand_id, name asc")
  end

  # GET /models/1
  # GET /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to @model, notice: 'Model was successfully updated.' }
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to models_url, notice: 'Model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:brand_id, :name, :photo)
    end
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/models/_form.html.erb
<%= form_for(@model, html: {class: 'form-horizontal', role: 'form', multipart: true}) do |f| %>
    <% if @model.errors.any? %>
        <div id="error_explanation" class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model
            from being saved:</h2>
          <ul>
            <% @model.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :brand_id, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.select :brand_id, Brand.all.map { |a| [a.name, a.id] }, {}, {class: 'form-control'} %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :name, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :photo, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= image_tag(@model.photo_url) if @model.photo? %>
        <%= f.file_field :photo %>
        <%= f.hidden_field :photo_cache, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= button_tag(type: 'submit', class: "btn btn-success") { "<i class='glyphicon glyphicon-floppy-disk'></i>".html_safe } %>
      </div>
    </div>

<% end %>

app/views/models/edit.html.erb
<div class="page-header">
<h1>Editing model</h1>
</div>

<%= render 'form' %>

<hr />

<fieldset>
  <div class="btn-group">
    <%= link_to "<i class='glyphicon glyphicon-arrow-left'></i>".html_safe, models_path, class: 'btn btn-default' %>
    <%= link_to "<i class='glyphicon glyphicon-search'></i>".html_safe, @model, class: 'btn btn-default' %>
  </div>
</fieldset>

app/views/models/index.html.erb
<div class="page-header">
  <h1>Listing models</h1>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Brand</th>
    <th>Name</th>
    <th>Photo</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @models.each do |model| %>
      <tr>
        <td><%= model.brand.name %></td>
        <td><%= model.name %></td>
        <td><%= image_tag (model.photo_url(:small_thumb).to_s) if model.photo? %>
        </td>
        <td>
          <div class="button-group">
            <%= link_to "<i class='glyphicon glyphicon-search'></i>".html_safe, model %>
            <%= link_to "<i class='glyphicon glyphicon-edit'></i>".html_safe, edit_model_path(model) %>
            <%= link_to "<i class='glyphicon glyphicon-trash red'></i>".html_safe, model, method: :delete, data: {confirm: 'Are you sure?'} %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<hr/>

<fieldset><%= link_to "<i class='glyphicon glyphicon-plus'></i>".html_safe, new_model_path, class: 'btn btn-success' %>
</fieldset>

app/views/models/new.html.erb
<div class="page-header">
  <h1>New model</h1>
</div>

<%= render 'form' %>

<hr/>


<fieldset>
  <%= link_to "<i class='glyphicon glyphicon-arrow-left'></i>".html_safe, models_path, class: 'btn btn-default' %>
</fieldset>

app/views/models/show.html.erb
<div class="page-header">
  <h1>Viewing model</h1>
</div>

<p id="notice"></p>

    <p>
      <strong>Brand:</strong>
      <%= @model.brand.name %>
    </p>

    <p>
      <strong>Name:</strong>
      <%= @model.name %>
    </p>

    <p>
      <strong>Photo:</strong>
      <%= image_tag(@model.photo) %>
    </p>


<fieldset>
  <div class="btn-group">
    <%= link_to "<i class='glyphicon glyphicon-arrow-left'></i>".html_safe, models_path, class: 'btn btn-default' %>
    <%= link_to "<i class='glyphicon glyphicon-edit'></i>".html_safe, edit_model_path(@model), class: 'btn btn-default' %>
    <%= link_to "<i class='glyphicon glyphicon-plus'></i>".html_safe, new_model_path, class: 'btn btn-success' %>
  </div>
</fieldset>