config/routes.rb
Dtscms::Application.routes.draw do
  
  resources :descriptions

  resources :models

  resources :brands

  root "pages#home"
  
  get "/home", to: "pages#home", as: "home"
  
  get "/signin", to: "sessions#new", as: "signin"
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: "signout"
  
  namespace :admin do
    root "base#index"
    resources :users
  end
    
end

app/models/description.rb
include ActionView::Helpers::SanitizeHelper

class Description < ActiveRecord::Base

  belongs_to :brand
  belongs_to :model

  # before_save :strip_html
  def strip_html # Automatically strips any tags from any string to text typed column
    self.description = strip_tags(description)
  end

end

app/controllers/descriptions_controller.rb
class DescriptionsController < ApplicationController
  before_action :set_description, only: [:show, :edit, :update, :destroy]

  # GET /descriptions
  # GET /descriptions.json
  def index
    # @descriptions = Description.all.order("brand_id, model_id") #.includes(:brand).order("brands.name asc")
    @processed = Description.where(processed: true).order("brand_id, model_id")
    @unprocessed = Description.where(processed: false).order("brand_id, model_id")
  end

  # GET /descriptions/1
  # GET /descriptions/1.json
  def show
  end

  # GET /descriptions/new
  def new
    @description = Description.new
  end

  # GET /descriptions/1/edit
  def edit
  end

  # POST /descriptions
  # POST /descriptions.json
  def create
    @description = Description.new(description_params)

    respond_to do |format|
      if @description.save
        format.html { redirect_to @description, notice: 'Description was successfully created.' }
        format.json { render :show, status: :created, location: @description }
      else
        format.html { render :new }
        format.json { render json: @description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /descriptions/1
  # PATCH/PUT /descriptions/1.json
  def update
    respond_to do |format|
      if @description.update(description_params)
        format.html { redirect_to @description, notice: 'Description was successfully updated.' }
        format.json { render :show, status: :ok, location: @description }
      else
        format.html { render :edit }
        format.json { render json: @description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /descriptions/1
  # DELETE /descriptions/1.json
  def destroy
    @description.destroy
    respond_to do |format|
      format.html { redirect_to descriptions_url, notice: 'Description was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_description
      @description = Description.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def description_params
      params.require(:description).permit(:brand_id, :model_id, :description, :processed)
    end
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/views/descriptions/_form.html.erb
<%= form_for(@description, html: {class: 'form-horizontal', role: 'form'}) do |f| %>
    <% if @description.errors.any? %>
        <div id="error_explanation" class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h2><%= pluralize(@description.errors.count, "error") %> prohibited this description
            from being saved:</h2>
          <ul>
            <% @description.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :brand_id, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.select :brand_id, Brand.all.map { |a| [a.name, a.id] }, {}, {class: 'form-control'} %>
          </div>
    </div>
    <div class="form-group">
      <%= f.label :model_id, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.select :model_id, Model.all.map { |a| [a.name, a.id] }, {}, {class: 'form-control'} %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :description, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.text_area :description, class: 'form-control', id: "edit" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :processed, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.check_box :processed, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= button_tag(type: 'submit', class: "btn btn-success") { "<i class='glyphicon glyphicon-floppy-disk'></i>".html_safe } %>
      </div>
    </div>

<% end %>

app/views/descriptions/edit.html.erb
<div class="page-header">
<h1>Editing description</h1>
</div>

<%= render 'form' %>

<hr />

<fieldset>
  <div class="btn-group">
    <%= link_to "<i class='glyphicon glyphicon-arrow-left'></i>".html_safe, descriptions_path, class: 'btn btn-default' %>
    <%= link_to "<i class='glyphicon glyphicon-search'></i>".html_safe, @description, class: 'btn btn-default' %>
  </div>
</fieldset>

app/views/descriptions/index.html.erb
<div class="page-header">
  <h1>Listing descriptions</h1>
</div>

<div class="bs-prods">
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#unprocessed">Unprocessed</a></li>
    <li><a data-toggle="tab" href="#roccessed">Processed</a></li>
  </ul>
  <div class="tab-content">
    <div id="unprocessed" class="tab-pane fade in active">
      <h3>Unprocessed</h3>

      <table class="table table-striped">
        <thead>
        <tr>
          <th>Brand</th>
          <th>Model</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
        </thead>

        <tbody>
        <% @unprocessed.each do |description| %>
            <tr>
              <td><%= description.brand.name %></td>
              <td><%= description.model.name %></td>
              <td><%= description.description.html_safe %></td>
              <td>
                <div class="button-group">
                  <%= link_to "<i class='glyphicon glyphicon-search'></i>".html_safe, description %>
                  <%= link_to "<i class='glyphicon glyphicon-edit'></i>".html_safe, edit_description_path(description) %>
                  <%= link_to "<i class='glyphicon glyphicon-trash red'></i>".html_safe, description, method: :delete, data: {confirm: 'Are you sure?'} %>
                </div>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>


    </div>
    <div id="roccessed" class="tab-pane fade">
      <h3>Processed</h3>


      <table class="table table-striped">
        <thead>
        <tr>
          <th>Brand</th>
          <th>Model</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
        </thead>

        <tbody>
        <% @processed.each do |description| %>
            <tr>
              <td><%= description.brand.name %></td>
              <td><%= description.model.name %></td>
              <td><%= description.description.html_safe %></td>
              <td>
                <div class="button-group">
                  <%= link_to "<i class='glyphicon glyphicon-search'></i>".html_safe, description %>
                  <%= link_to "<i class='glyphicon glyphicon-edit'></i>".html_safe, edit_description_path(description) %>
                  <%= link_to "<i class='glyphicon glyphicon-trash red'></i>".html_safe, description, method: :delete, data: {confirm: 'Are you sure?'} %>
                </div>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>


    </div>
  </div>
</div>



<br>

<hr/>

<fieldset><%= link_to "<i class='glyphicon glyphicon-plus'></i>".html_safe, new_description_path, class: 'btn btn-success' %>
</fieldset>

app/views/descriptions/new.html.erb
<div class="page-header">
  <h1>New description</h1>
</div>

<%= render 'form' %>

<hr/>

<fieldset>
  <%= link_to "<i class='glyphicon glyphicon-arrow-left'></i>".html_safe, descriptions_path, class: 'btn btn-default' %>
</fieldset>

app/views/descriptions/show.html.erb
<div class="page-header">
  <h1>Viewing description</h1>
</div>

<p id="notice"></p>

    <p>
      <strong>Brand:</strong>
      <%= @description.brand_id %>
    </p>

    <p>
      <strong>Model:</strong>
      <%= @description.model_id %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @description.description.html_safe %>
    </p>


<fieldset>
  <div class="btn-group">
    <%= link_to "<i class='glyphicon glyphicon-arrow-left'></i>".html_safe, descriptions_path, class: 'btn btn-default' %>
    <%= link_to "<i class='glyphicon glyphicon-edit'></i>".html_safe, edit_description_path(@description), class: 'btn btn-default' %>
    <%= link_to "<i class='glyphicon glyphicon-plus'></i>".html_safe, new_description_path, class: 'btn btn-success' %>
  </div>
</fieldset>