config/routes.rb
Dtscms::Application.routes.draw do
  
  resources :descriptions

  resources :models

  resources :brands

  root "pages#home"
  
  get "/home", to: "pages#home", as: "home"
  
  get "/signin", to: "sessions#new", as: "signin"
  post "/signin", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: "signout"
  
  namespace :admin do
    root "base#index"
    resources :users
  end
    
end

app/models/brand.rb
class Brand < ActiveRecord::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :logo)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand, html: { class: 'form-horizontal', role: 'form' }) do |f| %>
<% if @brand.errors.any? %>
<div id="error_explanation" class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand
    from being saved:</h2>
  <ul>
    <% @brand.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

    <div class="form-group">
                    <%= f.label :name, class: "col-lg-2 control-label" %>
              <div class="col-lg-10">
                <%= f.text_field :name, class: 'form-control' %>
              </div>
          </div>
    <div class="form-group">
                    <%= f.label :logo, class: "col-lg-2 control-label" %>
              <div class="col-lg-10">
                <%= f.text_field :logo, class: 'form-control' %>
              </div>
          </div>

<div class="form-group">
  <div class="col-lg-offset-2 col-lg-10">
    <%= button_tag(type: 'submit', class: "btn btn-success") {"<i class='glyphicon glyphicon-floppy-disk'></i>".html_safe } %>
  </div>
</div>

<% end %>

app/views/brands/edit.html.erb
<div class="page-header">
<h1>Editing brand</h1>
</div>

<%= render 'form' %>

<hr />

<fieldset>
  <div class="btn-group">
    <%= link_to "<i class='glyphicon glyphicon-arrow-left'></i>".html_safe, brands_path, class: 'btn btn-default' %>
    <%= link_to "<i class='glyphicon glyphicon-search'></i>".html_safe, @brand, class: 'btn btn-default' %>
  </div>
</fieldset>

app/views/brands/index.html.erb
<div class="page-header">
  <h1>Listing brands</h1>
</div>

<table class="table table-striped">
  <thead>
  <tr>
            <th>Name</th>
            <th>Logo</th>
        <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @brands.each do |brand| %>
  <tr>
            <td><%= brand.name %></td>
            <td><%= brand.logo %></td>
        <td>
      <div class="button-group">
        <%= link_to "<i class='glyphicon glyphicon-search'></i>".html_safe, brand %>
        <%= link_to "<i class='glyphicon glyphicon-edit'></i>".html_safe, edit_brand_path(brand) %>
        <%= link_to "<i class='glyphicon glyphicon-trash red'></i>".html_safe, brand, method: :delete, data:{ confirm: 'Are you sure?' } %>
      </div>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>

<br>

<hr/>

<fieldset><%= link_to "<i class='glyphicon glyphicon-plus'></i>".html_safe, new_brand_path, class: 'btn btn-success' %>
</fieldset>

app/views/brands/new.html.erb
<div class="page-header">
  <h1>New brand</h1>
</div>

<%= render 'form' %>

<hr/>


<fieldset>
  <%= link_to "<i class='glyphicon glyphicon-arrow-left'></i>".html_safe, brands_path, class: 'btn btn-default' %>
</fieldset>

app/views/brands/show.html.erb
<div class="page-header">
  <h1>Viewing brand</h1>
</div>

<p id="notice"></p>

    <p>
      <strong>Name:</strong>
      <%= @brand.name %>
    </p>

    <p>
      <strong>Logo:</strong>
      <%= @brand.logo %>
    </p>


<fieldset>
  <div class="btn-group">
    <%= link_to "<i class='glyphicon glyphicon-arrow-left'></i>".html_safe, brands_path, class: 'btn btn-default' %>
    <%= link_to "<i class='glyphicon glyphicon-edit'></i>".html_safe, edit_brand_path(@brand), class: 'btn btn-default' %>
    <%= link_to "<i class='glyphicon glyphicon-plus'></i>".html_safe, new_brand_path, class: 'btn btn-success' %>
  </div>
</fieldset>